#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# battery notification
$scripts/default/battery_notif &

# screen locking when idle
$scripts/default/idle_handler &

# effects
# $scripts/rgb &

## make kde connect work  (source: https://www.reddit.com/r/kde/comments/l6t6qu/please_make_kdeconnectcli_work_in_headless_moded/)
/usr/lib/kdeconnectd -platform offscreen & 
## Gnome authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
